steps:
  
# Docker Deploy Image from Artifact Registry
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - app
      - deploy
      - --image-url=$_SERVICE_IMAGE:latest
    env:
      - DEFAULT_DATABASE_IP_ADDRESS=172.22.0.3
    secretEnv: ['DEFAULT_SECRET_PASSWORD']
    dir: src

# Gettin Secrets from Secret Manager
availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/chess-db-user-password/versions/1'
    env: 'DEFAULT_SECRET_PASSWORD'

# Define variables
substitutions:
    _SERVICE_IMAGE          : ${_SERVICE_REGION}-docker.pkg.dev/chess-test-webapp-5/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}
    _SERVICE_REGION         : europe-central2
    _DOCKER_REGISTRY        : chess-application
    _DOCKER_IMAGENAME       : chess-staging

images:
- '$_SERVICE_IMAGE:latest'
- '$_SERVICE_IMAGE:$COMMIT_SHA'
- '$_SERVICE_IMAGE:$BUILD_ID'
