steps:

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'restore'
      - 'Web/Chess.Web/Chess.Web.csproj'
    id: 'RESTORE'
    dir: 'src'

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'build'
      - '-c'
      - 'Release'
    id: 'BUILD'
    dir: 'src'

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'test'
      - '-c'
      - 'Release'
    id: 'TEST'
    dir: 'src'

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'publish'
      - '-c'
      - 'Release'
      - '-o'
      - '/app/publish'
    id: 'PUBLISH'
    dir: 'src'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: 
      - '-c'
      - 'cp -t /app/publish/ app.yaml Dockerfile'
    id: 'PREPARE TO DEPLOY'
    dir: 'webapp'
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: 
      - '-c'
      - 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy'
    id: 'DEPLOY'
    dir: 'webapp'
    timeout: '1600s'