steps:

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'restore'
      - 'Web/Chess.Web/Chess.Web.csproj'
    id: 'RESTORE'
    dir: 'src'

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'build'
      - 'Chess.Web.csproj'
      - '--configuration Release'
      - '-o /app/build'
    id: 'BUILD'
    dir: '/src/Web/Chess.Web'

  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'dotnet'
    args:
      - 'build'
      - '-c Release'
    id: 'TEST'
    dir: '/app/build'