steps:

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'restore'
  #     - 'Web/Chess.Web/Chess.Web.csproj'
  #   id: 'RESTORE'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'build'
  #     - '-c'
  #     - 'Release'
  #   id: 'BUILD'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'test'
  #     - '-c'
  #     - 'Release'
  #   id: 'TEST'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'publish'
  #     - '-c'
  #     - 'Release'
  #     - '-o'
  #     - 'webapp'
  #   id: 'PUBLISH'
  #   dir: 'src'

  
  - name: gcr.io/cloud-builders/docker
    args: 
     - 'build'
     - '-t'
     - '$_SERVICE_IMAGE:${SHORT_SHA}'
     - '-t'
     - '$_SERVICE_IMAGE:$COMMIT_SHA'
     - '-t'
     - '$_SERVICE_IMAGE:$BUILD_ID'
     - '--build-arg=DB_CHESS_USER_PASSWORD=$$DB_CHESS_USER_PASSWORD'
     - '.'
     - '-f'
     - 'Dockerfile'
    id: 'BUILD'
    dir: 'src'
    timeout: '1600s'
    secretEnv: ['DB_CHESS_USER_PASSWORD']

# Test Image Docker Artifact 
  - name: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    id  : TEST
    args:
      - test
      - --image-url=$_SERVICE_IMAGE:$COMMIT_SHA

# Docker Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id  : PUSH
    args: ['push', '$_SERVICE_IMAGE:$COMMIT_SHA']

# Docker Deploy Image from Artifact Registry
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - app
      - deploy
      - --image-url=$_SERVICE_IMAGE:$COMMIT_SHA
    dir: src

availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/chess-db-user-password/versions/1'
    env: 'DB_CHESS_USER_PASSWORD'

substitutions:
    _SERVICE_IMAGE    : ${_SERVICE_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}
    _SERVICE_REGION   : europe-central2
    _DOCKER_REGISTRY  : chess-application
    _DOCKER_IMAGENAME : chess-staging