steps:

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'restore'
  #     - 'Web/Chess.Web/Chess.Web.csproj'
  #   id: 'RESTORE'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'build'
  #     - '-c'
  #     - 'Release'
  #   id: 'BUILD'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'test'
  #     - '-c'
  #     - 'Release'
  #   id: 'TEST'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'publish'
  #     - '-c'
  #     - 'Release'
  #     - '-o'
  #     - 'webapp'
  #   id: 'PUBLISH'
  #   dir: 'src'

  
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: 
     - -c
     - |
        docker build -t gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA} --build-args=DB_CHESS_USER_PASSWORD=$$DB_CHESS_USER_PASSWORD .
    # args: 
    #   - '-c'
    #   - 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy'
    id: 'DEPLOY'
    dir: 'src'
    timeout: '1600s'
    secretEnv: ['DB_CHESS_USER_PASSWORD']

availableSecrets:
  secretManager:
  - versionName: 'projects/chess-test-webapp-5/secrets/chess-db-user-password/versions/1'
    env: 'DB_CHESS_USER_PASSWORD'