steps:

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'restore'
  #     - 'Web/Chess.Web/Chess.Web.csproj'
  #   id: 'RESTORE'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'build'
  #     - '-c'
  #     - 'Release'
  #   id: 'BUILD'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'test'
  #     - '-c'
  #     - 'Release'
  #   id: 'TEST'
  #   dir: 'src'

  # - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  #   entrypoint: 'dotnet'
  #   args:
  #     - 'publish'
  #     - '-c'
  #     - 'Release'
  #     - '-o'
  #     - 'webapp'
  #   id: 'PUBLISH'
  #   dir: 'src'

  
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: 
     - 'build'
     - '-t'
     - 'gcr.io/$PROJECT_ID/chess-application:$COMMIT_SHA'
     - '--build-arg=DB_CHESS_USER_PASSWORD=$$DB_CHESS_USER_PASSWORD'
     - '.'
     - '-f'
     - 'Dockerfile'
    id: 'BUILD'
    dir: 'src'
    timeout: '1600s'
    secretEnv: ['DB_CHESS_USER_PASSWORD']

availableSecrets:
  secretManager:
  - versionName: 'projects/chess-test-webapp-5/secrets/chess-db-user-password/versions/1'
    env: 'DB_CHESS_USER_PASSWORD'